apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Node roles will be auto-added by eksctl
    # Add GitHub Actions IAM role here if using role
  mapUsers: |
    - userarn: arn:aws:iam::688567276212:user/github-actions-user
      username: github-actions
      groups:
        - system:masters
