apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::688567276212:role/eksctl-yolo-eks-cluster-nodegroup--NodeInstanceRole-BaUh4GVm0j1V
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::688567276212:role/eksctl-yolo-eks-cluster-nodegroup--NodeInstanceRole-Nu61GHpyMZPP
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::688567276212:user/github-actions-user
      username: github-actions
      groups:
        - system:masters