apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-config
  namespace: yolo-inference
data:
  S3_BUCKET: "${S3_BUCKET}"
  S3_MODEL_KEY: "${S3_MODEL_KEY}"
  AWS_REGION: "${AWS_REGION}"
  MODEL_PATH: "${MODEL_PATH}"
  OUTPUT_PATH: "${OUTPUT_PATH}"
  INFERENCE_DEVICE: "${INFERENCE_DEVICE}"
