apiVersion: v1
kind: ServiceAccount
metadata:
  name: yolo-sa
  namespace: yolo-inference
  annotations:
    # Replace ACCOUNT_ID with your AWS Account ID
    # Replace ROLE_NAME with your IAM role name
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/yolo-eks-pod-role
